# ci is a way where we develop our software such that it is always in a deployment state
name: Build CI Pipeline

on:
  push:
    branches:
      - main  # Ensure this matches the branch you want to trigger on

jobs:
  project-testing: # Name of the job or that could be any
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install necessary dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run DVC pipeline
        run: |
          dvc repro
